##########################################
# Docker full media server configuration #
##########################################
version: '3'

services:
  # File shares
  samba:
    image: dperson/samba
    command:
      - -w WORKGROUP
      - -u "reynn;${DEFAULT_PASSWORD}"
      - -u "dizkaimo;${DEFAULT_PASSWORD}"
      - -s "hamakaze;/media/hamakaze;yes;no;;;;;"
      - -s "isokaze;/media/isokaze;yes;no;;;;;"
      - -s "kawakaze;/media/kawakaze;yes;no;;;;;"
      - -s "shimakaze;/media/shimakaze;yes;no;;;;;"
      - -s "tokitsukaze;/media/tokitsukaze;yes;no;;;;;"
      - -s "yukikaze;/media/yukikaze;yes;no;;;;;"
    volumes:
      - /media:/media:rw
    ports:
      - 139:139
      - 445:445
    restart: always
  # Movie downloads
  couchpotato:
    image: linuxserver/couchpotato
    volumes:
      - /docker/containers/media-server/couchpotato:/config
      - /media:/media:rw
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30001:5050
    restart: always
  # TV Show downloads
  sonarr:
    image: linuxserver/sonarr
    volumes:
      - /docker/containers/media-server/sonarr:/config
      - /media:/media:rw
      - /dev/rtc:/dev/rtc:ro
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30002:8989
    restart: always
  sabnzb:
    image: linuxserver/sabnzbd
    volumes:
      - /docker/containers/media-server/sabnzb:/config:rw
      - /media/urakaze:/media/urakaze:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30003:8080
      - 40001:9090
    restart: always
  # Torrent downloader
  deluge:
    build: deluge-custom/
    image: deluge-custom
    volumes:
      - /docker/containers/media-server/deluge:/config
      - /media:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    network_mode: "host"
    restart: always
  # Media Server
  plex:
    build: plex/
    image: plex-custom
    volumes:
      - /docker/containers/media-server/plex:/config
      - /media:/mnt:rw
    environment:
      - VERSION=latest
      - PGID=1000
      - PUID=1000
    network_mode: "host"
    restart: always
  # Allows people to request movies/tv shows that will download through sonarr or couchpotato
  plexrequests:
    image: linuxserver/plexrequests
    volumes:
      - /docker/containers/media-server/plexrequests:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
      - URL_BASE=/requests
    ports:
      - 30004:3000
    restart: always
  # Collects stats for your Plex server
  tautulli:
    image: linuxserver/plexpy
    volumes:
      - /docker/containers/media-server/plexpy:/config
      - /docker/containers/media-server/logs/plexpy:/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
      - TZ="Americas\Los Angeles"
    ports:
      - 30005:8181
    restart: always
  # Ebook management
  calibre:
    image: linuxserver/calibre-web
    volumes:
      - /docker/containers/media-server/calibre:/config
      - /media:/media
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30006:8083
    restart: always
  # Comic downloader
  mylar:
    image: linuxserver/mylar
    volumes:
      - /docker/containers/media-server/mylar:/config
      - /media:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30007:8090
    restart: always
