##########################################
# Docker full media server configuration #
##########################################
version: '2'

services:
  # Movie downloads
  couchpotato:
    image: linuxserver/couchpotato
    volumes:
      - $HOME/dev/docker_containers/couchpotato:/config
      - /media:/media:rw
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30001:5050
    restart: always
  # TV Show downloads
  sonar:
    image: linuxserver/sonarr
    volumes:
      - $HOME/dev/docker_containers/sonarr:/config
      - /media:/media:rw
      - /dev/rtc:/dev/rtc:ro
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30002:8989
    restart: always
  sabnzb:
    image: linuxserver/sabnzbd
    volumes:
      - $HOME/dev/docker_containers/sabnzb:/config:rw
      - /media/urakaze:/media/urakaze:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30003:8080
      - 40001:9090
    restart: always
  # Torrent downloader
  deluge:
    build: deluge-custom/.
    image: deluge-custom
    volumes:
      - $HOME/dev/docker_containers/deluge:/config
      - /media:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    network_mode: "host"
    restart: always
  # Media Server
  plex:
    image: linuxserver/plex
    volumes:
      - $HOME/dev/docker_containers/plex:/config
      - /media:/mnt:rw
    environment:
      - VERSION=latest
      - PGID=1000
      - PUID=1000
    network_mode: "host"
    restart: always
  # Allows people to request movies/tv shows that will download through sonarr or couchpotato
  plexrequests:
    image: lsiodev/plexrequests
    volumes:
      - $HOME/dev/docker_containers/plexrequests:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30004:3000
    restart: always
  # Collects stats for your Plex server
  plexpy:
    image: linuxserver/plexpy
    volumes:
      - $HOME/dev/docker_containers/plexpy:/config
      - $HOME/dev/docker_containers/plexpy_logs:/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30005:8181
    restart: always
 # Comic downloader
  mylar:
    image: linuxserver/mylar
    volumes:
      - $HOME/dev/docker_containers/mylar:/config
      - /media:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 30007:8090
    restart: always



